# Generated by Django 6.0.4 on 2026-05-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0005_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Tranzaksiya', 'verbose_name_plural': "Tranzaksiyalar-(O'tkazmalar)"},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=12, verbose_name='Miqdori'),
        ),
    ]
