# Generated by Django 6.0.4 on 2026-05-06 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0009_transaction_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='product_name',
        ),
    ]
