# Generated by Django 6.0.4 on 2026-05-06 14:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0010_remove_transaction_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='product_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Maxsulot nomi'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
