# Generated by Django 6.0.4 on 2026-05-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0012_alter_cart_created_alter_cart_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Miqdori'),
        ),
    ]
