# Generated by Django 6.0.4 on 2026-05-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0013_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sariflangan pul miqdori'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Xarid vaqti'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='product_name',
            field=models.CharField(max_length=255, verbose_name='Maxsulot nomi'),
        ),
    ]
